[package]
name = "libunftp"
version = "0.13.1"
authors = [
    "Agoston Horvath <ahorvath@bol.com>",
    "Dávid Kosztka <dkosztka@bol.com>",
    "Hannes de Jager <hdejager@bol.com>",
    "Koen Wilde <koen@chillheid.nl>",
    "Maarten Dirkse <mdirkse@bol.com>",
    "Steven Meunier <smeunier@bol.com>",
    "Rob klein Gunnewiek <rkleingunnewiek@bol.com>",
   ]
description = "Extensible, async, cloud orientated FTP(S) server library."
documentation = "https://docs.rs/libunftp/"
repository = "https://github.com/bolcom/libunftp"
license = "Apache-2.0"
readme = "README.md"
keywords = ["ftp", "ftps"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
async-trait = "0.1.41"
bytes = "0.5.6"
chrono = {version = "0.4.19", features = ["serde"]}
derive_more = { version = "0.99.11", features = ["display"] }
futures = {version = "0.3.7", features = ["std"]}
hyper = { version = "0.13.8", optional = true, features= ["runtime", "stream"]}
hyper-rustls = {version = "0.21.0", optional = true}
itertools = "0.9.0"
lazy_static = "1.4.0"
libc = "0.2.79"
mime = {version = "0.3.16", optional = true}
path_abs = "0.5.0"
percent-encoding = { version = "2.1.0", optional = true }
prometheus = "0.10.0"
proxy-protocol = {version = "0.1.1"}
rand = "0.7.3"
regex = "1.4.1"
rustls = "0.18.1"
serde = { version = "1.0.117", optional = true, features = ["derive"] }
serde_json = { version = "1.0.59", optional = true }
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_info"] }
slog-stdlog = "4.1.0"
thiserror = "1.0.21"
tokio = { version = "0.3.2", features = ["rt", "net", "sync", "io-util", "macros", "time", "fs"]}
tokio-compat-02 = { version = "0.1.2", optional = true}
tokio-rustls = { version = "0.20.0" }
tokio-util = { version = "0.4.0", features=["codec", "compat"] }
tracing = "0.1.21"
tracing-attributes = "0.1.11"
tracing-futures = { version = "0.2.4", features = ["std", "std-future", "futures-03"]}
uuid = { version = "0.8.1", features = ["v4"] }
yup-oauth2 = {version = "4.1.3", optional = true}

[target.'cfg(unix)'.dependencies]
pam-auth = { package = "pam", version = "0.7.0", optional = true }

[dev-dependencies]
async_ftp = "4.0.2"
clap = "2.33.3"
log = "0.4.11"
pretty_assertions = "0.6.1"
pretty_env_logger = "0.4.0"
tempfile = "3.1.0"
tokio = { version = "0.3.2", features = ["rt-multi-thread"]}
tracing-subscriber = "0.2.14"

[features]
pam_auth = ["pam-auth"]
rest_auth = ["hyper", "percent-encoding", "serde", "serde_json", "tokio-compat-02"]
jsonfile_auth = ["serde", "serde_json"]
cloud_storage = ["oauth2", "mime", "percent-encoding", "hyper", "serde", "serde_json", "tokio-compat-02"]
oauth2 = ["yup-oauth2", "hyper-rustls", "tokio-compat-02"]

[[example]]
name = "gcs"
required-features = ["cloud_storage"]

[[example]]
name = "rest"
required-features = ["rest_auth"]

[[example]]
name = "jsonfile_auth"
required-features = ["jsonfile_auth"]

[[test]]
name = "gcs"
path = "tests/gcs.rs"
required-features = ["cloud_storage"]

[profile.release]
lto = "fat"
codegen-units = 1

[package.metadata.docs.rs]
all-features = true

